---
 custom: false
 wall_w: 0.3 # width of side walls.
 floor_s: 20 # Creates a x by x floor, where x := floor_s
 floor_h: 0.001 # Height of floor.
 n_obs: 15 # No. of obstacles.
 obs_h: 0.25 # Height of obstacles.
 obs_w: 1.0 # Width of obstacles.
 goal_w: 0.5 # Width of goal.
 goal_h: 0.25 # Height of goal
 goal_loc: null # Randomly placed if `null`
 wall_color: '#B80C09'
 obs_color: '#040F16'
 goal_color: '#01BAEF'
 floor_color: '#FBFBFF'
